version: 0.2

phases:
  pre_build:
    commands:
      - echo "Testing basic pipeline"
      - echo "Testing ECR login..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo "Build phase working"
      - echo "Testing Next.js application build..."
      - echo "Building Docker image for CandidStance app..."
      - docker build --build-arg OPENAI_API_KEY=$OPENAI_API_KEY --build-arg GOOGLE_API_KEY=$GOOGLE_API_KEY -t candidstance-app .
      - echo "Successfully built CandidStance app image"

  post_build:
    commands:
      - echo "Post build phase working"
      - echo "Testing Docker push..."
      - docker tag candidstance-app $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:latest
      - echo '{"ImageURI":"candidstance-app"}' > imageDefinitions.json

artifacts:
  files:
    - imageDefinitions.json
